# Generated by Django 3.2 on 2023-05-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230526_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='pub_date',
        ),
    ]
